---
title: "Flavour of the month (August 2024) : Focus on ZIKA virus"
date:   2024-08-01 15:43:37 +0000
---

**Abstract:**

Zika virus is an emerging mosquito-borne virus of concern for public health, but very little is known about its transmission patterns and ecology, especially in African countries. Here, we expanded the genomic information by sequencing Zika viruses isolated from mosquitoes collected in Kedougou, Senegal, located in Western Africa. All new genomes are part of the African genotype, within the virus lineage previously characterized as the Western Lineage. Sequences were strongly clustered by sampling location and date of the collection respectively, suggesting a highly focal geographical and temporal distribution. Our phylogeographic reconstructions indicated that the African genotype of the Zika virus Western Lineage emerged in the Western part of Africa mostly following an East-to-West migration pattern. The analyses further revealed that the African genotype of the Zika virus was likely introduced in Western Africa between 1957 and 1974. Since the emergence of the Zika virus in Western Africa, we found a decrease in the effective population size of the Zika virus Western Lineage, but stagnating in recent years in the Kedougou region. Over time, no significant increase was recorded in the CAI values for A. aegypti and H. sapiens. In summary, the integrated results indicate that the African genotype ZIKV continues to circulate in forest areas, using sylvatic mosquitoes as vectors in Western Africa, with a long period of persistence at a local scale, with an accumulation of diversity over time, and without any evidence of adaptation based in CAI values to the urban environment.

**Keywords** : Zika virus; African genotype; Senegal; Western Lineage; Western Africa