project:
  type: website
  output-dir: docs

website:
  favicon: ./files/avatar.jpg
  title: "ArboDiaGen"
  navbar:
    logo: ./files/image.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: The Scientist
      - href: DreamTeam.qmd
        text: The Dream Team
      - href: La Masia.qmd
        text: La Masia
      - href: PublishedArticles.qmd
        text: Publications
      - href: Flavour.qmd
        text: Flavour of the Month
      - href: OpenScience.qmd
        text: Open Science
      - href: Devtools.qmd
        text: Developed Tools
      - href: Knowshare.qmd
        text: Knowledge Sharing
      - href: Scientific_Talk.qmd
        text: Scientific Talk
      - href: Scientific.qmd
        text: Scientific Communications
format:
  html:
    theme:
      light: cosmmo
      dark: sandstone
    css: styles.css
    toc: true



