project:
  type: website
  output-dir: docs

website:
  title: "ArboDiaGen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: The Scientist
      - href: DreamTeam.qmd
        text: The Dream Team
      - href: PublishedArticles.qmd
        text: Publications
      - href: Flavour.qmd
        text: Flavour of the Month
      - href: OpenScience.qmd
        text: Open Science
      - href: Devtools.qmd
        text: Developed Tools


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



