---
title: "List of publications Updates 06/08/2024"
page-layout: full
title-block-banner: true
comments: false
---

1. [CDC Trioplex diagnostic assay underperforms in detection of circulating Chikungunya West African genotype](https://journals.asm.org/doi/epub/10.1128/jcm.00405-24)


2. [Genomic characterization of a reemerging Chikungunya outbreak in Kedougou, Southeastern Senegal, 2023](https://www.tandfonline.com/doi/10.1080/22221751.2024.2373308)


3. [An amplicon-based Illumina and nanopore sequencing workflow for Chikungunya virus West Africa genotype](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10723560/)


4. [Reemergence of Sylvatic Dengue Virus Serotype 2 in Kedougou, Senegal, 2020](https://wwwnc.cdc.gov/eid/article/30/4/23-1301_article)


5. [Molecular Evolution of Dengue Virus 3 in Senegal between 2009 and 2022: Dispersal Patterns and Implications for Prevention and Therapeutic Countermeasures](https://www.mdpi.com/2076-393X/11/10/1537)

6. [Analysis of a Dengue Virus Outbreak in Rosso, Senegal 2021](https://www.mdpi.com/2414-6366/7/12/420)

7. [Identification of Pathogens Potentially Associated with Non-Malarial Fever in Children: A Pilot Study in Peri-Urban Dakar, Senegal](https://www.ajtmh.org/view/journals/tpmd/104/4/article-p1335.xml)

8. [Full genome analysis of circulating DENV-2 in Senegal reveals a regional diversification into separate clades](https://onlinelibrary.wiley.com/doi/10.1002/jmv.28027)

9. [Dengue virus serotype 2 imported case from Côte d'Ivoire to Senegal, 2017](https://onlinelibrary.wiley.com/doi/10.1111/tbed.14239)

10. [Quantitative real time PCR detection of Saboya virus: A flavivirus member of yellow fever genetic group](https://www.sciencedirect.com/science/article/pii/S0166093422001860?via%3Dihub)

11. [Origin and Spread of the Dengue Virus Type 1, Genotype V in Senegal, 2015-2019](https://www.mdpi.com/1999-4915/13/1/57)

12. [Re-Emergence of Dengue Serotype 3 in the Context of a Large Religious Gathering Event in Touba, Senegal](https://www.mdpi.com/1660-4601/19/24/16912)

13. [Molecular characterization of circulating Dengue virus 2 during an outbreak in Northern Senegal's Saint-Louis region in 2018](https://onlinelibrary.wiley.com/doi/10.1002/jmv.28347)

14. [Multifoci and multiserotypes circulation of dengue virus in Senegal between 2017 and 2018](https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-021-06580-z)

15. [A new lineage nomenclature to aid genomic surveillance of dengue virus](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1111864)

16. [Detection of Crimean Congo haemorrhagic fever virus in North-eastern Senegal, Bokidiawé 2019](https://www.tandfonline.com/doi/full/10.1080/22221751.2020.1847605)

17. [Molecular Detection and Genetic Characterization of Two Dugbe Orthonairovirus Isolates Detected from Ticks in Southern Senegal](https://www.mdpi.com/1999-4915/16/6/964)

18. [Field Deployment of a Mobile Biosafety Laboratory Reveals the Co-Circulation of Dengue Viruses Serotype 1 and Serotype 2 in Louga City, Senegal, 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8032538/)

19. [Genomic Characterization of a Bataï Orthobunyavirus, Previously Classified as Ilesha Virus, from Field-Caught Mosquitoes in Senegal, Bandia 1969](https://www.mdpi.com/1999-4915/16/2/261)

20. [Mobile Laboratory Reveals the Circulation of Dengue Virus Serotype I of Asian Origin in Medina Gounass (Guediawaye), Senegal](https://www.mdpi.com/2075-4418/10/6/408)

21. [The Spatiotemporal Distribution and Molecular Characterization of Circulating Dengue Virus Serotypes/Genotypes in Senegal from 2019 to 2023](https://www.mdpi.com/2414-6366/9/2/32)













